### ISSUE TITLE
missing headers?

### ISSUE THREAD

**Issue by marcopompili** [SeanPesce/d3d11-wrapper#1]
Hi Sean,

I opened your solution in VS 2017, but I can't find some headers under the SP folder, like:
`sp/main.h`, `sp/main/preferences.h`, `sp/log.h`

**Comment by SeanPesce** [comment]
Sorry about that; those headers are from my personal utility library. I should have included it as a submodule, but for now you can download them ~~[here](https://github.com/SeanPesce/d3d11-wrapper/files/2255570/lib.zip)~~ [here](https://github.com/SeanPesce/d3d11-wrapper/files/4434546/lib.zip). Unfortunately I'm out of town for several days so I can't confirm it's the right version of the library, but if you're still having trouble getting it to work I can help sometime next week.


~~[lib.zip](https://github.com/SeanPesce/d3d11-wrapper/files/2255570/lib.zip)~~
[lib.zip](https://github.com/SeanPesce/d3d11-wrapper/files/4434546/lib.zip)

**Comment by marcopompili** [comment]
I suspected it was your personal library, the _sp_ prefix gave me that clue. I was able to build your project using the zip you sent me.

Thank you

**Comment by SeanPesce** [comment]
Glad to hear it's resolved! Just a heads up, I actually have a ton of un-pushed code from ~2 months ago that'll add some overlay-drawing functionality, so once I sort that out and push the changes you'll probably want to pull again.

**Comment by CookiePLMonster** [comment]
FWIW this zip only contains 64-bit libraries, so this wrapper still can't be built for 32-bit apps.

**Comment by SeanPesce** [comment]
You're right; not sure why I chose to leave out the 32-bit library files. Everything seems to compile correctly with [these libraries (32-bit and 64-bit)](https://github.com/SeanPesce/d3d11-wrapper/files/4434546/lib.zip); hopefully there are no other issues, as I haven't worked on this project in almost 2 years, and I'm not as familiar with the code base as I once was.

If you run into compilation issues, try disabling ["whole program optimization"](https://stackoverflow.com/questions/837073/error-c1047-object-file-created-with-an-older-compiler-than-other-objects) for the release build configurations.

[lib.zip](https://github.com/SeanPesce/d3d11-wrapper/files/4434546/lib.zip)
